FROM python:3.13-slim
WORKDIR /app
COPY requirements.frontend.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY frontend ./frontend
EXPOSE 8001
CMD ["uvicorn", "frontend.main:app", "--host", "0.0.0.0", "--port", "8001"]
